[www]
listen = /run/teebravo-php/fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660
pm = ondemand
pm.max_children = 3
pm.process_idle_timeout = 15s
pm.max_requests = 500
clear_env = no
